services:
  ta-organizer:
    # build: .  <-- Uncomment to build locally
    image: ghcr.io/salpertio/ta-organizerr:latest
    container_name: ta-organizer
    volumes:
      - ./source:/app/source
      - ./target:/app/target
      - ./data:/app/data
      - ./import:/app/import
    ports:
      - "8002:5000"
    environment:
      - SCAN_INTERVAL=60
      - ALLOWED_IPS=127.0.0.1,192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
      # - UI_USERNAME=admin
      # - UI_PASSWORD=password
      # env_file: .env
