services:
  ta-organizer:
    build: /mnt/user/appdata/dockerbuildings
    container_name: ta-organizer
    volumes:
      - /mnt/user/appdata/dockerbuildings/source:/app/source:ro
      - /mnt/user/appdata/dockerbuildings/target:/app/target
    environment:
      - SCAN_INTERVAL=${SCAN_INTERVAL:-60}
    env_file: /mnt/user/appdata/dockerbuildings/.env
